name: Linux Workflow
on: [push]
jobs:
  main:
    name: Run Workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Say Hi
        run: |
          echo "Hello World"
      - name: Download and Install Miniconda
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
          bash ~/miniconda.sh -b
          export PATH=~/miniconda3/bin:$PATH
          conda update --yes conda
      - name: Create Conda Environment
        run: |
          conda env create -f environment.yml
          conda run -n actions-mwe python --version  # https://pythonspeed.com/articles/activate-conda-dockerfile/
          
          
    
